title: Gabriel Menezes
logo: https://github.com/GabrielMenezes1997/GabrielMenezes1997.github.io/blob/main/1634134826280.jpg?raw=true
description: Cornell University MSBA 2025
#show_downloads: false
theme: jekyll-theme-minimal
