title: Gabriel Menezes


logo: https://github.com/GabrielMenezes1997/GabrielMenezes1997.github.io/blob/main/Picture_circular.jpg?raw=true


description: "**Business Analytics Projects**"
#show_downloads: false
theme: jekyll-theme-minimal
